---
title: "Report from Shiny WebApp"
output:
  pdf_document:
    latex_engine: lualatex
    toc: true
    number_sections: true
    df_print: kable
mainfont: Arial
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
params:
  dwn_dat: NA
  dwn_meta: NA
  dwn_sbgrp: NA
  dwn_metareg: NA
  dwn_pb: NA
  dat: NA
  metric: NA
  k: NA
  n: NA
  in_study: NA
  model_type: NA
  k_meta: NA
  estim: NA
  meta_es: NA
  meta_se: NA
  meta_ci.lb: NA
  meta_ci.ub: NA
  meta_pval: NA
  meta_zval: NA
  meta_tau2: NA
  meta_I2: NA
  meta_H2: NA
  qtest_df: NA
  qtest_stat: NA
  qtest_pval: NA
  sbgrp_k: NA
  sbgrp_tau2: NA
  sbgrp_se.tau2: NA
  sbgrp_I2: NA
  sbgrp_H2: NA
  sbgrp_R2: NA
  sbgrp_Qdf: NA
  sbgrp_QE: NA
  sbgrp_QEp: NA
  sbgrp_QM: NA
  sbgrp_QM_knha: NA
  sbgrp_QMp: NA
  sbgrp_QMp_knha: NA
  sbgrp_df_coeff: NA
  pb_bm_tau: NA
  pb_bm_pval: NA
  thres_bm_pval: NA
  pb_se_zval: NA
  pb_se_pval: NA
  thres_se_pval: NA
  pb_tf_k: NA
  pb_tf_side: NA
  pb_tf_es: NA
  thres_tf_adj: NA
  pb_pcurve_restab: NA
  pb_pcurve_powertab: NA
  pb_pcurve_pval.full: NA
  pb_pcurve_pval.half: NA
  pb_tes_o: NA
  pb_tes_e: NA
  pb_tes_pval: NA
  pb_tes_res: NA
  thres_tes_pval: NA
  pb_sel_mod1: NA
  pb_sel_sev1: NA
  pb_sel_mod2: NA
  pb_sel_sev2: NA
  thres_sel_adj: NA
  pb_sel_perc_mod1: NA
  pb_sel_perc_sev1: NA
  pb_sel_perc_mod2: NA
  pb_sel_perc_sev2: NA
  pb_sel_unadj: NA
  pb_puni_zval: NA
  pb_puni_pval: NA
  pb_punistar_zval: NA
  pb_punistar_pval: NA
  thres_puni_pval: NA
  thres_punistar_pval: NA
---

```{r bias_ind, include = FALSE}

bias_bm <- ifelse(params$pb_bm_pval < params$thres_bm_pval, "bias", "no bias")
bias_se <- ifelse(params$pb_se_pval < params$thres_se_pval, "bias", "no bias")
bias_tf <- ifelse((params$meta_es - params$pb_tf_es)/params$meta_es < params$thres_tf_adj, "no bias", "bias")
bias_puni <- ifelse(params$pb_puni_pval < params$thres_puni_pval, "bias", "no bias")
bias_punistar <- ifelse(params$pb_punistar_pval < params$thres_punistar_pval, "bias", "no bias")
bias_pcurve <- ifelse((params$pb_pcurve_pval.half < 0.05) | ((params$pb_pcurve_pval.half < 0.1) & params$pb_pcurve_pval.full < 0.1), "no bias", "bias")
bias_tes <- ifelse((params$pb_tes_pval < params$thres_tes_pval) & (params$pb_tes_e < params$pb_tes_o), "bias", "no bias")
bias_selmod <- ifelse(c(params$pb_sel_perc_mod1, params$pb_sel_perc_sev1, params$pb_sel_perc_mod2, params$pb_sel_perc_sev2) < params$thres_sel_adj, "no bias", "bias")

```


\newpage
```{r child_dat, child=if (params$dwn_dat) here('report_child_dat.Rmd')}
```

```{r child_meta, child=if (params$dwn_meta) here('report_child_meta.Rmd')}
```

```{r child_sbgrp, child=if (params$dwn_sbgrp) here('report_child_sbgrp.Rmd')}
```

```{r child_metareg, child=if (params$dwn_metareg) here('report_child_metareg.Rmd')}
```

```{r child_pb, child=if (params$dwn_pb) here('report_child_pb.Rmd')}
```



# References