---
title: "report_child_pb"
output:
  pdf_document:
    latex_engine: lualatex
    toc: true
    number_sections: true
    df_print: kable
mainfont: Arial
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
params:
  dwn_pb_bm: NA
  dwn_pb_se: NA
  dwn_pb_tf: NA
  dwn_pb_pcurve: NA
  dwn_pb_puni: NA
  dwn_pb_selmods: NA
  dwn_pb_tes: NA
  pb_bm_tau: NA
  pb_bm_pval: NA
  thres_bm_pval: NA
  pb_se_zval: NA
  pb_se_pval: NA
  thres_se_pval: NA
  pb_tf_k: NA
  pb_tf_side: NA
  pb_tf_es: NA
  thres_tf_adj: NA
  pb_pcurve_restab: NA
  pb_pcurve_powertab: NA
  pb_pcurve_pval.full: NA
  pb_pcurve_pval.half: NA
  pb_tes_o: NA
  pb_tes_e: NA
  pb_tes_pval: NA
  pb_tes_res: NA
  thres_tes_pval: NA
  pb_sel_mod1: NA
  pb_sel_sev1: NA
  pb_sel_mod2: NA
  pb_sel_sev2: NA
  thres_sel_adj: NA
  pb_sel_perc_mod1: NA
  pb_sel_perc_sev1: NA
  pb_sel_perc_mod2: NA
  pb_sel_perc_sev2: NA
  pb_sel_unadj: NA
  pb_puni_zval: NA
  pb_puni_pval: NA
  pb_punistar_zval: NA
  pb_punistar_pval: NA
  thres_puni_pval: NA
  thres_punistar_pval: NA
---

```{r bias_ind, include = FALSE}

bias_bm <- "Not investigated"
bias_se <- "Not investigated"
bias_tf <- "Not investigated"
bias_puni <- "Not investigated"
bias_punistar <- "Not investigated"
bias_pcurve <- "Not investigated"
bias_tes <- "Not investigated"
bias_selmod <- rep("Not investigated", 4)

```

# Publication Bias Methods

```{r child_pb_bm, child=if (params$dwn_pb_bm) here('report_child_pb_bm.Rmd')}
```

```{r child_pb_se, child=if (params$dwn_pb_se) here('report_child_pb_se.Rmd')}
```

```{r child_pb_tf, child=if (params$dwn_pb_tf) here('report_child_pb_tf.Rmd')}
```

```{r child_pb_pcurve, child=if (params$dwn_pb_pcurve) here('report_child_pb_pcurve.Rmd')}
```

```{r child_pb_puni, child=if (params$dwn_pb_puni) here('report_child_pb_puni.Rmd')}
```

```{r child_pb_selmods, child=if (params$dwn_pb_selmods) here('report_child_pb_selmods.Rmd')}
```

```{r child_pb_tes, child=if (params$dwn_pb_tes) here('report_child_pb_tes.Rmd')}
```

## Summary of Bias Indication

## Summary of Bias Analyses

```{r, summarytab, echo = FALSE}

method <- c("Begg & Mazumdar's Rank Test",
             "Sterne & Egger's Regression",
             "Trim-and-Fill",
             "p-uniform",
             "p-uniform*",
             "p-curve",
             "Test of Excess Significance",
             "Selection Models: Moderate one-tailed",
             "Selection Models: Severe one-tailed",
             "Selection Models: Moderate two-tailed",
             "Selection Models: Severe two-tailed")

bias_methods <- c(bias_bm, 
                  bias_se,
                  bias_tf,
                  bias_puni,
                  bias_punistar,
                  bias_pcurve,
                  bias_tes,
                  bias_selmod)

bias <- ifelse(bias_methods == "bias", "Bias Indication", 
               ifelse(bias_methods == "no bias", "No Bias Indication", bias_methods))


df.summary <- data.frame(
  Method = method,
  Bias = bias
)


#df.summary$Bias = kableExtra::cell_spec(df.summary$Bias,
#                           background = factor(df.summary$Bias,c("Bias Indication", "No Bias Indication")
#                                              , c("#666666", "#999999")))


kableExtra::kbl(df.summary, booktabs = TRUE) %>% 
  kableExtra::column_spec(2, background = ifelse(df.summary$Bias == "Bias Indication", "#ec6f6f", 
                                                 ifelse(df.summary$Bias == "No Bias Indication", "#7dec6f",
                                                        "#d3d3d3"))) %>%
  kable_styling(position = "center")
```